### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by TheAIguy-dev** [venaxyt/mysterium#25] opened 2022-06-13 20:00 UTC
When I run mysterium, i get this message:
![1](https://user-images.githubusercontent.com/90064221/173434644-5444f1eb-ad17-4980-b341-3f5f5de8b70c.png)
But when I run this program with python, it absolutely works.

NOTE: abi/standart.json exists.

**Comment by novakdwy** [comment] 2022-07-25 12:39
You're program is trying to use a file that doesn't exist, just create this file in the written directory './abi/standard.json'.

**Comment by TheAIprod** [comment] 2022-07-27 07:41
It already exists

> You're program is trying to use a file that doesn't exist, just create this file in the written directory './abi/standard.json'.

It already exists

**Comment by eljeffeg** [comment] 2022-10-04 15:55
I was getting an issue where I would supply the uninspected file (zip) and then specify the obfuscated file name (script.py) and it would come back that it couldn't find `modules\script.py`.  I have no idea why it was searching for modules as the dir structure was `dist/script.py`.

**Comment by eljeffeg** [comment] 2022-10-04 16:10
After looking at the code, looks Mysterium extracts the zip to it's modules folder and then looks for the file in question.
So might make sense to also look for a `dist` directory before failing out, so `'file' or 'dist/file'`.

After testing, it gets further along but fails to load the PyArmor with `RuntimeError: Marshal loads failed`

**Comment by venaxyt** [comment] 2023-05-01 12:34
> After looking at the code, looks Mysterium extracts the zip to it's modules folder and then looks for the file in question. So might make sense to also look for a `dist` directory before failing out, so `'file' or 'dist/file'`.
> 
> After testing, it gets further along but fails to load the PyArmor with `RuntimeError: Marshal loads failed`

Sorry for responding so late. Anyways, the problem is the same as Bad magic number or wrong opcode etc....
That means you're trying to run the decompiled program with a different Python version than the one used by its creator.
If you want it to work, you have two solutions. The first one needs the source executable, you have to decompile it with the tool you use, for example pyinstxtractor for pyinstaller, (pyarmor compilation uses pyinstaller), and so you'll see the Python version used to compile it by the script owner in the decompilation logs in your console. The second option is to use my tool I sell on the Telegram account in Mysterium's documentation, at the end. The tool doesn't need the exe if you don't have it, but it still works with it. There are methods it uses to detect which Python version is the right one by reading some details in the encrypted code file i hope my response was able to help you, I let the issue open some weeks if you still have to get any help.

**Comment by venaxyt** [comment] 2023-08-01 21:48
I see that there are no more activity here so I'm going to close the issue, I guess you resolved the problem with your missing file.

**Closed by venaxyt** 2023-08-01 21:48 UTC
